nbrb:
  url: https://api.nbrb.by

spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: nbrb
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        jdbc:
          batch_size: 10
          order_inserts: true
        generate_statistics: true
    show-sql: true
  h2:
    console:
      enabled: true

  mvc:
    format:
      date: yyyy-MM-dd

  liquibase:
    enabled: true