nbrb:
  url: https://api.nbrb.by
  spring:
    datasource:
      url: jdbc:h2:mem:nbrbdb
      username: nbrb
      password: pass
      driver-class-name: org.h2.Driver
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
      show-sql: true