nbrb:
  url: https://api.nbrb.by
  spring:
    datasource:
      url: jdbc:h2:file:/data/demo
      username: nbrb
      password: pass
      driver-class-name: org.h2.Driver

    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
      show-sql: true

    mvc:
      format:
        date: yyyy-MM-dd